#!/bin/bash

# qvdraw
# Takes all inputted matrices and produces a picture of their quivers.

count=1

function draw {
	matrix="$@"
	cmd="qv2gml -m \"${matrix}\" | gmlayout > tmp.gml"
	eval $cmd
	gml2pic -o ${count}.png tmp.gml > /dev/null
	rm -f tmp.gml
	count=$((count+1))
}

f="$1"

while read p
do
	draw $p
done < $f

