#!/bin/bash

# qvdraw
# Takes all inputted matrices and produces a picture of their quivers.

count=1

flag="$1"
if [ "$flag" == "-h" ]; then
	echo "qvdraw [-n] [filename]"
	echo "If no filename is specified then input is taken from stdin."
	echo "  -n Do not draw arrows on quivers. "
	exit
fi
if [ "$1" == "-n" ]; then
	arrow=true
	shift
fi

function draw {
	matrix="$@"
	cmd="qv2gml -m \"${matrix}\" | gmlayout > tmp.gml"
	eval $cmd
	opt="-msg-level silent"
	if [ $arrow ]
	then
		opt="$opt -arrows none"
	fi
	dcmd="gml2pic $opt -o ${count}.png tmp.gml > /dev/null"
	eval $dcmd
	rm -f tmp.gml
	count=$((count+1))
}

# Check number of parameters, if there are none, assume that input is stdin
# otherwise the input comes from the file named in the parameter.
if [ "$#" -eq 0 ]
then
	while read p
	do
		draw "$p"
	done
else
	f="$1"
	while read p
	do
		draw "$p"
	done < $f
fi

